import { Suspense } from "react";
import type { Metadata } from "next";
import { Great_Vibes, Outfit, Red_Hat_Display } from "next/font/google";

import Header from "@/components/Header";

import "./globals.css";

import Providers from "@/providers";
import SideModal from "@/SideModal";

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--great-vibes-font",
});

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--red-hat-display-font",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--outfit-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${greatVibes.variable} ${redHatDisplay.variable} ${outfit.variable}`}
      >
        <Providers>
          <Suspense>
            <Header />
          </Suspense>
          <main>{children}</main>
          <SideModal />
        </Providers>
      </body>
    </html>
  );
}
